create table "public"."concerts"
(
    "id"     bigint generated by default as identity not null,
    "name"   text                                    not null,
    "active" boolean                                 not null default true,
    constraint "concerts_pkey" primary key ("id")
);

create table "public"."global_settings"
(
    "id"      bigint generated by default as identity not null,
    "key"     text                                    not null,
    "value"   text,
    "private" boolean                                 not null default false,
    constraint "global_settings_pkey" primary key ("id")
);

create table "public"."instruments"
(
    "id"     bigint generated by default as identity not null,
    "name"   text                                    not null,
    "tuning" bigint                                  not null default '0',
    constraint "instruments_pkey" primary key ("id")
);

create table "public"."orchestras"
(
    "id"   bigint generated by default as identity not null,
    "name" text                                    not null,
    constraint "orchestras_pkey" primary key ("id")
);

create table "public"."pieces"
(
    "id"   bigint generated by default as identity not null,
    "name" text                                    not null,
    constraint "pieces_pkey" primary key ("id")
);

create table "public"."files"
(
    "id"        bigint generated by default as identity not null,
    "piece_id"  bigint                                  not null,
    "file_path" text                                    not null,
    "version"   bigint                                  not null default '0',
    constraint "files_pkey" primary key ("id"),
    constraint "files_piece_id_fkey" foreign key ("piece_id") references "public"."pieces" ("id") on delete cascade,
    constraint "unique_version_piece_id_file_path" unique ("version", "piece_id", "file_path")
);

create table "public"."user_settings"
(
    "id"       bigint generated by default as identity not null,
    "user_id"  uuid                                    not null default auth.uid(),
    "key"      text                                    not null,
    "value"    text,
    "private"  boolean                                 not null default false,
    "readonly" boolean                                 not null default false,
    constraint "user_settings_pkey" primary key ("id"),
    constraint "user_settings_user_id_fkey" foreign key ("user_id") references "auth"."users" ("id") on delete cascade
);

create table "public"."concert_orchestras"
(
    "id"           bigint generated by default as identity not null,
    "concert_id"   bigint                                  not null,
    "orchestra_id" bigint                                  not null,
    constraint "concert_orchestras_pkey" primary key ("id"),
    constraint "concert_orchestras_concert_id_fkey" foreign key ("concert_id") references "public"."concerts" ("id") on delete cascade,
    constraint "concert_orchestras_orchestra_id_fkey" foreign key ("orchestra_id") references "public"."orchestras" ("id") on delete cascade
);

create table "public"."concert_pieces"
(
    "id"         bigint generated by default as identity not null,
    "piece_id"   bigint                                  not null,
    "concert_id" bigint                                  not null,
    constraint "concert_pieces_pkey" primary key ("id"),
    constraint "concert_pieces_piece_id_fkey" foreign key ("piece_id") references "public"."pieces" ("id") on delete cascade,
    constraint "concert_pieces_concert_id_fkey" foreign key ("concert_id") references "public"."concerts" ("id") on delete cascade
);

create table "public"."orchestra_pieces"
(
    "id"           bigint generated by default as identity not null,
    "piece_id"     bigint                                  not null,
    "orchestra_id" bigint                                  not null,
    constraint "orchestra_pieces_pkey" primary key ("id"),
    constraint "orchestra_pieces_piece_id_fkey" foreign key ("piece_id") references "public"."pieces" ("id") on delete cascade,
    constraint "orchestra_pieces_orchestra_id_fkey" foreign key ("orchestra_id") references "public"."orchestras" ("id") on delete cascade
);

create table "public"."file_instruments"
(
    "id"            bigint generated by default as identity not null,
    "instrument_id" bigint                                  not null,
    "file_id"       bigint                                  not null,
    constraint "file_instruments_pkey" primary key ("id"),
    constraint "file_instruments_instrument_id_fkey" foreign key ("instrument_id") references "public"."instruments" ("id") on delete cascade,
    constraint "file_instruments_file_id_fkey" foreign key ("file_id") references "public"."files" ("id") on delete cascade
);

create table "public"."instrument_concert_orchestras"
(
    "id"            bigint generated by default as identity not null,
    "instrument_id" bigint                                  not null,
    "orchestra_id"  bigint                                  not null,
    "user_id"       uuid                                    not null,
    constraint "instrument_orchestra_pkey" primary key ("id"),
    constraint "instrument_concert_orchestras_instrument_id_fkey" foreign key ("instrument_id") references "public"."instruments" ("id") on delete cascade,
    constraint "instrument_concert_orchestras_orchestra_id_fkey" foreign key ("orchestra_id") references "public"."orchestras" ("id") on delete cascade,
    constraint "instrument_concert_orchestras_user_id_fkey" foreign key ("user_id") references "auth"."users" ("id") on delete cascade
);

alter table "public"."concerts" enable row level security;
alter table "public"."orchestras" enable row level security;
alter table "public"."pieces" enable row level security;
alter table "public"."instruments" enable row level security;
alter table "public"."concert_orchestras" enable row level security;
alter table "public"."concert_pieces" enable row level security;
alter table "public"."orchestra_pieces" enable row level security;
alter table "public"."files" enable row level security;
alter table "public"."file_instruments" enable row level security;
alter table "public"."instrument_concert_orchestras" enable row level security;
alter table "public"."global_settings" enable row level security;
alter table "public"."user_settings" enable row level security;

create
policy "Allow select if user can access a corresponding orchestra" on "public"."concerts"
    for
select using (id in (select concert_id from public.concert_orchestras));

create
policy "Enable read access for all users" on "public"."global_settings"
    for
select using (true);

create
policy "Enable read access for all users" on "public"."pieces"
    for
select using (true);

create
policy "Give access if user has access to instrument" on "public"."instruments"
    for
select using (id in (select instrument_id from public.instrument_concert_orchestras));

create
policy "Give access if user has access to instrument" on "public"."file_instruments"
    for
select using (instrument_id in (
    select instrument_concert_orchestras.instrument_id
    from public.instrument_concert_orchestras
    ));

create
policy "Give access if user has access to orchestra" on "public"."orchestra_pieces"
    for
select using (orchestra_id in (
    select orchestras.id
    from public.orchestras
    ));

create
policy "Give access if user has access to orchestra" on "public"."orchestras"
    for
select using (id in (
    select orchestra_id
    from public.instrument_concert_orchestras
    ));

create
policy "Give access if user has access to concert" on "public"."concert_pieces"
    for
select using (concert_id in (
    select concerts.id
    from public.concerts
    ));

create
policy "Give access if user can access orchestra" on "public"."concert_orchestras"
    for
select using (orchestra_id in (
    select orchestras.id
    from public.orchestras
    ));

create
policy "Give users access to their own data only" on "public"."instrument_concert_orchestras"
    for
select using ((select auth.uid()) = user_id);

create
policy "Restrict access to access to concert" on "public"."pieces"
    as restrictive
    for
select using (id in (
    select piece_id
    from public.concert_pieces
    ));

create
policy "Restrict access to access to orchestra" on "public"."pieces"
    as restrictive
    for
select using (id in (
    select piece_id
    from public.orchestra_pieces
    ));


create
policy "Give access if user has access to piece" on "public"."files"
for
select using (
    (select "files"."piece_id") in
    (select "pieces"."id" from "public"."pieces"));

create
policy "Restrict access to instrument" on "public"."files"
    as restrictive
    for
select using (id in (
    select file_id
    from public.file_instruments
    ));

create
policy "Give users access to their own data only" on "public"."user_settings"
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

create
policy "Restrict access to public" on "public"."user_settings"
    as restrictive
    using (not private)
    with check (not private);

create
policy "Restrict delete to writable" on "public"."user_settings"
    as restrictive
    for delete
using (not readonly);

create
policy "Restrict insert to writable" on "public"."user_settings"
    as restrictive
    for
insert with check (not readonly);

create
policy "Restrict update access to writable" on "public"."user_settings"
    as restrictive
    for
update using (not readonly)
with check (not readonly);

create
policy "Restrict to active concerts" on "public"."concerts"
    as restrictive
    for
select using (active);

create
policy "Restrict to public settings" on "public"."global_settings"
    as restrictive
    for
select using (not private);
