create table "public"."admins"
(
    "id"     bigint generated by default as identity not null,
    "user_id"  uuid                                  not null default auth.uid(),
    constraint "admins_pkey" primary key ("id"),
    constraint "admins_user_id_fkey" foreign key ("user_id") references "auth"."users" ("id") on delete cascade
);

alter table "public"."admins" enable row level security;

create
policy "Give users access to their own data" on "public"."admins"
    for
select using ((select auth.uid()) = user_id);